spring.application.name=coreBankingService
server.port=8082


spring.datasource.url=jdbc:postgresql://localhost:5432/core_banking_db
spring.datasource.username=postgres
spring.datasource.password=b123123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# RabbitMQ Ayarlar\u0131 (Transfer servisiyle ayn\u0131 olmal\u0131)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Dinlenecek Kuyruk Ad\u0131
rabbitmq.queue.transfer-created=transfer-created-queue
rabbitmq.exchange.transfer=transfer-exchange
rabbitmq.routing.key.transfer-created=transfer.created
rabbitmq.routing.key.transfer-completed=transfer.completed.key
rabbitmq.routing.key.transfer-failed=transfer.failed.key

jwt.secret=T0p1R3k4SjZNNU4yeThDOUxBcXpwVnc0RTZINXRCZ00=